apiVersion: apps/v1
kind: Deployment
metadata:
  name: lymc-frontend-deployment
  labels:
    app: lymc-frontend-deployment
spec:
  selector:
    matchLabels:
      app: lmyc-frontend-container
  template:
    metadata:
      labels:
        app: lmyc-frontend-container
    spec:
      containers:
        - image: public.ecr.aws/m2q6z9r8/lmyc-frontend-public:latest
          name: frontend
          ports:
            - containerPort: 3000
          env:
            # Used for requests coming from the browser
            - name: LMYC_BACKEND_HOST_EXTERNAL
              value: "http://lubricentromyc.com/backend/lubricentro_myc"
            # Used for requests coming from the NextJS server (getServerSideProps)
            - name: LMYC_BACKEND_HOST_INTERNAL
              value: "http://lmyc-backend-service:8000/lubricentro_myc"